config-version: 1.0
debug: false
enable-vault: false
vault-format: "원"

# 데이터 베이스 설정
database: 
  enable: false
  type: "mysql" 
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  name: "minecraft"

# 각 플러그인별 추가적인 타입 및 데이터 저장방식을 설정하는 설정
#
# 플러그인 이름:
#   타입이름:
# 위 같은 구조로 설정하며 각각 적용가능한 데이터 및 기본값은 다음과 같다
# enable:true
# saveType:"file"
# autoSave:300
# saveEvent:
# - "ONDISABLE"
# loadEvent:
# - "FIRSTLOADEVENT"
#
# 데이터를 넣지 않을 경우 기본값으로 진행하며 enable이 false일 경우 타입 데이터를 불러올 수 는 있으나 저장은 하지 않는다
# 해당 설정에서 만들지 않은 타입들을 불러올 경우 에러가 발생하게 된다.
#
# 설정된 플러그인이 로드 되지 않을 경우 무시하고 진행한다
#
# 해당 CommediaDellarte의 설정은 예시이며 수정 가능하다
#
# 기본적으로 모든 적용되는 플러그인에는 player,world,entity 기본으로 적용된다. 
# 각 기본 타입별로 적용되는 기본값이 다르다
# 만약 해당 타입을 적고 설정을 수정할 경우 해당 설정대로 적용된다.
data-storage: 
  CommediaDellarte:
    # player타입의 기본값
    player: 
      enable: true
      # 데이터 저장방식 설정 file, mysql이 있으며 그 외는 아직 개발중
      saveType: "file"
      # 자동 저장 설정 설정 된 초 마다 저장한다
      # -1로 할 경우 작동하지 않는다
      autoSave: 300
      # 데이터를 저장하는 시점을 이벤트로 지정하는 설정
      # 각 이벤트를 대문자로 적으면되며 각 이벤트가 발생할때 저장한다.
      # ONDISABLE를 적을 경우 플러그인이 OnDisable될때 데이터를 저장한다.
      saveEvent:
      - "ONDISABLE"
      # 데이터를 불러오는 시점을 이벤트로 지정하는 설정
      # 각 이벤트를 대문자로 적으면되며 각 이벤트가 발생할때 불러온다.
      # 서버가 켜질때 따로 데이터를 로드하지 않으며 사용자가 따로 데이터를 로드해줘야한다.
      # ONENABLE를 적을경우 서버가 켜지고 FirstLoadEvent이전에 데이터를 로드한다.
      # 이외에는 사용자가 직접 데이터를 로드해야한다.
      loadEvent:
      - "FIRSTLOADEVENT"
    # world타입의 기본값
    world:
      enable: true
      saveType: "file"
      autoSave: 300
      saveEvent:
      - "ONDISABLE"
      loadEvent:
      - "FIRSTLOADEVENT"
    # entity타입의 기본값
    entity:
      enable: true
      saveType: "file"
      autoSave: 300
      saveEvent:
      - "ONDISABLE"
      loadEvent:
      - "FIRSTLOADEVENT"
  

# area-event의 경우 설정 값을 변경하고 싶다면 서버를 껏다 켜야합니다.
area-event:
  # Player event
  AsyncPlayerChatEvent:
    enabled: true
  PlayerAdvancementDoneEvent:
    enabled: true
  PlayerAnimationEvent:
    enabled: true
  PlayerArmorStandManipulateEvent:
    enabled: true
  PlayerBedEnterEvent:
    enabled: true
  PlayerBedLeaveEvent:
    enabled: true
  PlayerBucketEmptyEvent:
    enabled: true
  PlayerBucketEntityEvent:
    enabled: true
  PlayerBucketFillEvent:
    enabled: true
  PlayerBucketFishEvent:
    enabled: true
  PlayerChangedMainHandEvent:
    enabled: true
  PlayerChangedWorldEvent:
    enabled: true
  PlayerChannelEvent:
    enabled: true
  PlayerCommandPreprocessEvent:
    enabled: true
  PlayerCommandSendEvent:
    enabled: true
  PlayerDropItemEvent:
    enabled: true
  PlayerEditBookEvent:
    enabled: true
  PlayerEggThrowEvent:
    enabled: true
  PlayerExpChangeEvent:
    enabled: true
  PlayerFishEvent:
    enabled: true
  PlayerGameModeChangeEvent:
    enabled: true
  PlayerHarvestBlockEvent:
    enabled: true
  PlayerInteractAtEntityEvent:
    enabled: true
  PlayerInteractEntityEvent:
    enabled: true
  PlayerInteractEvent:
    enabled: true
  PlayerItemBreakEvent:
    enabled: true
  PlayerItemConsumeEvent:
    enabled: true
  PlayerItemDamageEvent:
    enabled: true
  PlayerItemHeldEvent:
    enabled: true
  PlayerItemMendEvent:
    enabled: true
  PlayerJoinEvent:
    enabled: true
  PlayerKickEvent:
    enabled: true
  PlayerLevelChangeEvent:
    enabled: true
  PlayerLocaleChangeEvent:
    enabled: true
  PlayerLoginEvent:
    enabled: true
  PlayerMoveEvent:
    enabled: true
  PlayerPickupArrowEvent:
    enabled: true
  PlayerPickupItemEvent:
    enabled: true
  PlayerPortalEvent:
    enabled: true
  PlayerQuitEvent:
    enabled: true
  PlayerRecipeDiscoverEvent:
    enabled: true
  PlayerRegisterChannelEvent:
    enabled: true
  PlayerResourcePackStatusEvent:
    enabled: true
  PlayerRespawnEvent:
    enabled: true
  PlayerRiptideEvent:
    enabled: true
  PlayerShearEntityEvent:
    enabled: true
  PlayerStatisticIncrementEvent:
    enabled: true
  PlayerSwapHandItemsEvent:
    enabled: true
  PlayerTakeLecternBookEvent:
    enabled: true
  PlayerTeleportEvent:
    enabled: true
  PlayerToggleFlightEvent:
    enabled: true
  PlayerToggleSneakEvent:
    enabled: true
  PlayerToggleSprintEvent:
    enabled: true
  PlayerUnleashEntityEvent:
    enabled: true
  PlayerUnregisterChannelEvent:
    enabled: true
  PlayerVelocityEvent:
    enabled: true
  AreaEffectCloudApplyEvent:
    enabled: true
  ArrowBodyCountChangeEvent:
    enabled: true
  BatToggleSleepEvent:
    enabled: true
  CreatureSpawnEvent:
    enabled: true
  CreeperPowerEvent:
    enabled: true
  EnderDragonChangePhaseEvent:
    enabled: true
  EntityAirChangeEvent:
    enabled: true
  EntityBreakDoorEvent:
    enabled: true
  EntityBreedEvent:
    enabled: true
  EntityChangeBlockEvent:
    enabled: true
  EntityCombustByBlockEvent:
    enabled: true
  EntityCombustByEntityEvent:
    enabled: true
  EntityCombustEvent:
    enabled: true
  EntityCreatePortalEvent:
    enabled: true
  EntityDamageByBlockEvent:
    enabled: true
  EntityDamageByEntityEvent:
    enabled: true
  EntityDamageEvent:
    enabled: true
  EntityDeathEvent:
    enabled: true
  EntityDropItemEvent:
    enabled: true
  EntityEnterBlockEvent:
    enabled: true
  EntityEnterLoveModeEvent:
    enabled: true
  EntityEvent:
    enabled: true
  EntityExhaustionEvent:
    enabled: true
  EntityExplodeEvent:
    enabled: true
  EntityInteractEvent:
    enabled: true
  EntityPickupItemEvent:
    enabled: true
  EntityPlaceEvent:
    enabled: true
  EntityPortalEnterEvent:
    enabled: true
  EntityPortalEvent:
    enabled: true
  EntityPortalExitEvent:
    enabled: true
  EntityPoseChangeEvent:
    enabled: true
  EntityPotionEffectEvent:
    enabled: true
  EntityRegainHealthEvent:
    enabled: true
  EntityResurrectEvent:
    enabled: true
  EntityShootBowEvent:
    enabled: true
  EntitySpawnEvent:
    enabled: true
  EntitySpellCastEvent:
    enabled: true
  EntityTameEvent:
    enabled: true
  EntityTargetEvent:
    enabled: true
  EntityTargetLivingEntityEvent:
    enabled: true
  EntityTeleportEvent:
    enabled: true
  EntityToggleGlideEvent:
    enabled: true
  EntityToggleSwimEvent:
    enabled: true
  EntityTransformEvent:
    enabled: true
  EntityUnleashEvent:
    enabled: true
  ExpBottleEvent:
    enabled: true
  ExplosionPrimeEvent:
    enabled: true
  FireworkExplodeEvent:
    enabled: true
  FoodLevelChangeEvent:
    enabled: true
  HorseJumpEvent:
    enabled: true
  ItemDespawnEvent:
    enabled: true
  ItemMergeEvent:
    enabled: true
  ItemSpawnEvent:
    enabled: true
  LingeringPotionSplashEvent:
    enabled: true
  PiglinBarterEvent:
    enabled: true
  PigZapEvent:
    enabled: true
  PigZombieAngerEvent:
    enabled: true
  PlayerDeathEvent:
    enabled: true
  PlayerLeashEntityEvent:
    enabled: true
  PotionSplashEvent:
    enabled: true
  ProjectileHitEvent:
    enabled: true
  ProjectileLaunchEvent:
    enabled: true
  SheepDyeWoolEvent:
    enabled: true
  SheepRegrowWoolEvent:
    enabled: true
  SlimeSplitEvent:
    enabled: true
  SpawnerSpawnEvent:
    enabled: true
  StriderTemperatureChangeEvent:
    enabled: true
  VillagerAcquireTradeEvent:
    enabled: true
  VillagerCareerChangeEvent:
    enabled: true
  VillagerReplenishTradeEvent:
    enabled: true
  BlockBreakEvent:
    enabled: true
  BlockBurnEvent:
    enabled: true
  BlockCanBuildEvent:
    enabled: true
  BlockCookEvent:
    enabled: true
  BlockDamageEvent:
    enabled: true
  BlockDispenseArmorEvent:
    enabled: true
  BlockDispenseEvent:
    enabled: true
  BlockDropItemEvent:
    enabled: true
  BlockEvent:
    enabled: true
  BlockExpEvent:
    enabled: true
  BlockExplodeEvent:
    enabled: true
  BlockFadeEvent:
    enabled: true
  BlockFertilizeEvent:
    enabled: true
  BlockFormEvent:
    enabled: true
  BlockFromToEvent:
    enabled: true
  BlockGrowEvent:
    enabled: true
  BlockIgniteEvent:
    enabled: true
  BlockMultiPlaceEvent:
    enabled: true
  BlockPhysicsEvent:
    enabled: true
  BlockPistonExtendEvent:
    enabled: true
  BlockPistonRetractEvent:
    enabled: true
  BlockPlaceEvent:
    enabled: true
  BlockReceiveGameEvent:
    enabled: true
  BlockRedstoneEvent:
    enabled: true
  BlockShearEntityEvent:
    enabled: true
  BlockSpreadEvent:
    enabled: true
  CauldronLevelChangeEvent:
    enabled: true
  EntityBlockFormEvent:
    enabled: true
  FluidLevelChangeEvent:
    enabled: true
  LeavesDecayEvent:
    enabled: true
  MoistureChangeEvent:
    enabled: true
  NotePlayEvent:
    enabled: true
  SignChangeEvent:
    enabled: true
  SpongeAbsorbEvent:
    enabled: true

